name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRETS_230509 }}
          USERNAME: S-CHOI-S
      - name: Commit & Push
        run: |
          git pull origin main
          git checkout main
          git fetch origin
          git merge origin/main
          git config user.name S-CHOI-S
          git config user.email S-CHOI-S@github.com
          git add -A .
          git commit -m "generated"
          git push origin
          git pull
